require:
  - ./lib/rubocop/cop/spbtv/postgres/add_column_with_default
  - ./lib/rubocop/cop/spbtv/postgres/add_column_with_not_null
  - ./lib/rubocop/cop/spbtv/postgres/add_index
  - ./lib/rubocop/cop/spbtv/postgres/change_column
  - ./lib/rubocop/cop/spbtv/postgres/find_each
  - ./lib/rubocop/cop/spbtv/multiple_validation

# Rails:
#  Enabled: true

AllCops:
  Exclude:
    - '**/schema.rb'
    - '**/db/**/*'
    - '**/docs/**/*'
    - '**/tmp/**/*'
    - '**/vendor/**/*'

Style/Documentation:
  Exclude:
    - '**/spec/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/AsciiComments:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/Next:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/EmptyCaseCondition:
  Enabled: false

Metrics/ClassLength:
  Severity: refactor
  Max: 140
  Exclude:
    - '**/db/**/*'

Metrics/PerceivedComplexity:
  Severity: refactor

Metrics/ParameterLists:
  Severity: refactor

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Severity: refactor
  Exclude:
    - '**/db/**/*'

Metrics/MethodLength:
  Severity: refactor
  Max: 15
  Exclude:
    - '**/db/**/*'

Metrics/CyclomaticComplexity:
  Severity: refactor

Style/SignalException:
  EnforcedStyle: semantic

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Postgres/AddColumnWithDefault:
  Exclude:
    - '**/db/migrate/2015*'
    - '**/db/migrate/20160*'
    - '**/db/migrate/201610*'

Postgres/AddColumnWithNotNull:
  Exclude:
    - '**/db/migrate/2015*'
    - '**/db/migrate/20160*'
    - '**/db/migrate/201610*'

Postgres/AddIndex:
  Exclude:
    - '**/db/migrate/2015*'
    - '**/db/migrate/20160*'
    - '**/db/migrate/201610*'

Postgres/ChangeColumn:
  Exclude:
    - '**/db/migrate/2015*'
    - '**/db/migrate/20160*'
    - '**/db/migrate/201610*'

# Rails/NotNullColumn:
#   Enabled: false
