Rails:
 Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/AsciiComments:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/Next:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/TrivialAccessors:
  AllowPredicates: true

Style/IfUnlessModifier:
  MaxLineLength: 30

Metrics/AbcSize:
  Severity: refactor

Metrics/PerceivedComplexity:
  Severity: refactor

Metrics/ParameterLists:
  Severity: refactor

Metrics/MethodLength:
  Severity: refactor

Metrics/CyclomaticComplexity:
  Severity: refactor

Style/SignalException:
  EnforcedStyle: semantic
  
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented  
