require:
  - rubocop-rspec
  - ./lib/rubocop/cop/spbtv/postgres/add_column_with_default
  - ./lib/rubocop/cop/spbtv/postgres/add_column_with_not_null
  - ./lib/rubocop/cop/spbtv/postgres/add_index
  - ./lib/rubocop/cop/spbtv/postgres/change_column
  - ./lib/rubocop/cop/spbtv/multiple_validation

Rails:
 Enabled: true

AllCops:
  Exclude:
    - '**/schema.rb'
    - '**/db/**/*'
    - '**/docs/**/*'
    - '**/tmp/**/*'
    - '**/vendor/**/*'

Style/Documentation:
  Exclude:
    - '**/spec/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/AsciiComments:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/Next:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/IfUnlessModifier:
  MaxLineLength: 30

Style/EmptyCaseCondition:
  Enabled: false

Metrics/ClassLength:
  Severity: refactor
  Exclude:
    - '**/db/**/*'

Metrics/AbcSize:
  Severity: refactor

Metrics/PerceivedComplexity:
  Severity: refactor

Metrics/ParameterLists:
  Severity: refactor

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Severity: refactor
  Exclude:
    - '**/db/**/*'

Metrics/MethodLength:
  Severity: refactor
  Exclude:
    - '**/db/**/*'

Metrics/CyclomaticComplexity:
  Severity: refactor

Style/SignalException:
  EnforcedStyle: semantic

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/IndentArray:
  EnforcedStyle: consistent

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Postgres/AddColumnWithDefault:
  Exclude:
    - '**/db/migrate/2015*'
    - '**/db/migrate/20160*'
    - '**/db/migrate/201610*'

Postgres/AddColumnWithNotNull:
  Exclude:
    - '**/db/migrate/2015*'
    - '**/db/migrate/20160*'
    - '**/db/migrate/201610*'

Postgres/AddIndex:
  Exclude:
    - '**/db/migrate/2015*'
    - '**/db/migrate/20160*'
    - '**/db/migrate/201610*'

Postgres/ChangeColumn:
  Exclude:
    - '**/db/migrate/2015*'
    - '**/db/migrate/20160*'
    - '**/db/migrate/201610*'

Rails/NotNullColumn:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3
