Rails:
 Enabled: true

AllCops:
  Exclude:
    - '**/schema.rb'
    - '**/db/**/*'
    - '**/docs/**/*'
    - '**/tmp/**/*'
    - '**/vendor/**/*'

Style/Documentation:
  Exclude:
    - '**/spec/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/AsciiComments:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/Next:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/TrivialAccessors:
  AllowPredicates: true

Style/IfUnlessModifier:
  MaxLineLength: 30

Style/EmptyCaseCondition:
  Enabled: false

Metrics/AbcSize:
  Severity: refactor

Metrics/PerceivedComplexity:
  Severity: refactor

Metrics/ParameterLists:
  Severity: refactor

Metrics/MethodLength:
  Severity: refactor

Metrics/CyclomaticComplexity:
  Severity: refactor

Style/SignalException:
  EnforcedStyle: semantic

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/IndentArray:
  EnforcedStyle: consistent

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/FirstArrayElementLineBreak:
  Enabled: true

Style/FirstHashElementLineBreak:
  Enabled: true

Style/FirstMethodArgumentLineBreak:
  Enabled: true

Style/FirstMethodParameterLineBreak:
  Enabled: true
