inherit_from:
  - .rubocop.yml

Metrics/AbcSize:
  Severity: warning
  Exclude:
    - '**/db/**/*'

Metrics/PerceivedComplexity:
  Severity: warning

Metrics/ParameterLists:
  Severity: warning

Metrics/MethodLength:
  Severity: warning
  Exclude:
    - '**/db/**/*'

Metrics/CyclomaticComplexity:
  Severity: warning
