require 'rubocop'
require_relative 'cop/spbtv/postgres/add_column_with_default'
require_relative 'cop/spbtv/postgres/add_column_with_not_null'
require_relative 'cop/spbtv/postgres/add_index'
require_relative 'cop/spbtv/postgres/change_column'
require_relative 'cop/spbtv/postgres/find_each'
require_relative 'cop/spbtv/multiple_validation'
